services:
  autotrader:
    image: bluesman80/autotrader:latest
    container_name: autotrader
    # Using host network mode to pass the request IP to container
    network_mode: "host"
    # It's unnecessary to expose the port when using host network mode
    #    ports:
    #      - "8081:8081"
    environment:
      - TZ=Europe/Amsterdam
      - MONGODB_AUTOTRADER_USER=${MONGODB_AUTOTRADER_USER}
      - MONGODB_AUTOTRADER_PASSWORD=${MONGODB_AUTOTRADER_PASSWORD}
      - MONGODB_AUTOTRADER_URI=${MONGODB_AUTOTRADER_URI}
      - BITVAVO_API_URL=${BITVAVO_API_URL}
      - ENCRYPTION_MASTER_KEY=${ENCRYPTION_MASTER_KEY}
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs/autotrader:/app/logs
    restart: unless-stopped
