spring:
  application:
    name: autotrader
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_AUTOTRADER_USER}:${MONGODB_AUTOTRADER_PASSWORD}@${MONGODB_AUTOTRADER_URI}
      database: autotrader
      auto-index-creation: true

bitvavo:
  api:
    url: ${BITVAVO_API_URL}

# Encryption settings for sensitive data
encryption:
  master-key: ${ENCRYPTION_MASTER_KEY}  # Base64 encoded key, should be set via environment variable in production
