spring:
  application:
    name: autotrader

bitvavo:
  apiKey: ${BITVAVO_API_KEY}
  apiSecret: ${BITVAVO_API_SECRET}
  apiUrl: https://api.bitvavo.com/v2
  window: 10000   # Default window in milliseconds (10 seconds)
