name: Deploy to Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push with Maven
        run: mvn -B install -Ddocker.username=${{ secrets.DOCKERHUB_USERNAME }} -Ddocker.password=${{ secrets.DOCKERHUB_TOKEN }} --file pom.xml

      - name: Copy docker-compose.yml to Remote Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "docker-compose.yml"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_SSH_PORT }}
          TARGET: ${{ secrets.REMOTE_FINAL_TARGET }}/docker-compose-autotrader.yml
          SCRIPT_AFTER_REQUIRED: true

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Set environment variables
            export LOGS_PATH=${{ secrets.REMOTE_LOGS_PATH }}/autotrader
            export MONGODB_AUTOTRADER_USER=${{ secrets.MONGODB_AUTOTRADER_USER }}
            export MONGODB_AUTOTRADER_PASSWORD=${{ secrets.MONGODB_AUTOTRADER_PASSWORD }}
            export MONGODB_AUTOTRADER_URI=${{ secrets.MONGODB_AUTOTRADER_URI }}
            export BITVAVO_API_URL=${{ secrets.BITVAVO_API_URL }}
            export ENCRYPTION_MASTER_KEY=${{ secrets.ENCRYPTION_MASTER_KEY }}

            # Pull the latest image and restart the service
            docker compose -f ${{ secrets.REMOTE_FINAL_TARGET }}/docker-compose-autotrader.yml pull
            docker compose -f ${{ secrets.REMOTE_FINAL_TARGET }}/docker-compose-autotrader.yml up -d --remove-orphans
